name: Build PR

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write
  packages: write
  issues: write

env:
  IMAGE_BASE: "ghcr.io/${{ github.repository_owner }}/excalidraw"

jobs:
  generate_infos:
    uses: fullstack-devops/actions/.github/workflows/generate-build-infos.yml@main
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  build:
    runs-on: ubuntu-latest
    needs: generate_infos
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
      
      - name: get excalidraw version
        id: excalidraw_version
        run: echo "::set-output name=version::$(cat ./APP_VERSION)"

      - name: Check out excalidraw
        uses: actions/checkout@v3
        with:
          repository: 'excalidraw/excalidraw'
          path: excalidraw
          ref: v${{ steps.excalidraw_version.outputs.version }}
          
      - name: install packages
        working-directory: excalidraw
        run: yarn --ignore-optional
      - name: build application
        working-directory: excalidraw
        run: yarn build

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build excalidraw:pr-${{ github.event.pull_request.number }}
        uses: docker/build-push-action@v2
        with:
          context: ./
          push: true
          build-args: APP_VERSION=${{ steps.excalidraw_version.outputs.version }}
          tags: |
            ${{ env.IMAGE_BASE }}:pr-${{ github.event.pull_request.number }}
