name: Build PR

on:
  pull_request:

env:
  IMAGE_BASE: "ghcr.io/${{ github.repository_owner }}/excalidraw"

jobs:
  generate_infos:
    uses: fullstack-devops/actions/.github/workflows/generate-build-infos.yml@main
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}

  build:
    runs-on: ubuntu-latest
    needs: generate_infos
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build excalidraw:pr-${{ github.event.pull_request.number }}
        uses: docker/build-push-action@v2
        with:
          context: ./
          push: true
          tags: |
            ${{ env.IMAGE_BASE }}:pr-${{ github.event.pull_request.number }}
